// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxGRSGpwfBzwy3BZ_dbkWDObrjLSoIAzc',
    appId: '1:764087551371:web:04708c3bbaac8ef8f7db8e',
    messagingSenderId: '764087551371',
    projectId: 'iot-packet-box',
    authDomain: 'iot-packet-box.firebaseapp.com',
    databaseURL: 'https://iot-packet-box-default-rtdb.firebaseio.com',
    storageBucket: 'iot-packet-box.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmiqn0XQXRjEakL2niH0LICs-8qqFlNLc',
    appId: '1:764087551371:android:48c648fe6f639938f7db8e',
    messagingSenderId: '764087551371',
    projectId: 'iot-packet-box',
    databaseURL: 'https://iot-packet-box-default-rtdb.firebaseio.com',
    storageBucket: 'iot-packet-box.firebasestorage.app',
  );
}
